config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :blogs
  end
  resources :blogs
  get 'home/index'
  get 'payments/new'
  get 'payments/create'
  namespace :admin do
    resources :orders
    resources :order_items
    resources :parts
    resources :users

    root to: "orders#index"
  end
  # Devise routes for user authentication
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Resources for parts
  resources :parts do
    post 'add_to_cart', on: :member
    get 'add_to_cart_js', on: :member
    get 'search', on: :collection
    post :import, on: :collection
    get :export, on: :collection
    get :download_export, on: :collection
  end

  # Resources for orders
  resources :orders

  # Root route
  root 'home#index'

  # Additional routes
  get 'pages/about'
  get 'pages/contact'

  resources :payments, only: [:new, :create] do
    collection do
      post :capture_order
    end
  end
  get 'success', to: 'payments#success' # Create success action
  get 'error', to: 'payments#error'     # Create error action

end

app/models/part.rb
# app/models/part.rb
class Part < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items
  belongs_to :model
  belongs_to :year
  
  has_many_attached :images

  validates :item_part_number, presence: true
  validates :part_number, presence: true

  # Searchable attributes
  def self.ransackable_attributes(auth_object = nil)
    %w[
      item_part_number
      part_number
      name
      description
      package_level_gtin
      height
      width
      length
      shipping_height
      shipping_width
      shipping_length
      weight
      attribute_name
      price
      product_attribute
    ]
  end

  # Searchable associations
  def self.ransackable_associations(auth_object = nil)
    %w[order_items orders images_attachments images_blobs]
  end
end

app/controllers/admin/parts_controller.rb
module Admin
  class PartsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  
  def index
    if params[:search].present? && params[:search_type].present?
      search_term = params[:search]
      case params[:search_type]
      when 'vehicle'
        @parts = Part.joins(:model, :year).where('models.name ILIKE :search', search: "%#{search_term}%")
      when 'part_number'
        @parts = Part.where('part_number ILIKE :search', search: "%#{search_term}%")
      when 'part_type'
        @parts = Part.where('description ILIKE :search', search: "%#{search_term}%")
      else
        @parts = Part.all
      end
    else
      @parts = Part.all
    end
  end

  def search
    @q = Part.joins(model: :make).ransack(params[:q])
    @parts = @q.result(distinct: true)
    render partial: 'parts/part_list', locals: { parts: @parts }
  end

  def show
    @part = Part.find(params[:id])
    session[:cart] ||= []
  end

  def add_to_cart
    part_id = params[:id].to_i
    session[:cart] ||= []
    if params[:id].present? && !session[:cart].include?(part_id)
      session[:cart] << part_id 
      cart_count = session[:cart].count
      render json: { status: 'Successfuly added' }
    else
      render json: { status: 'Already added' }
    end
  end

  def new
    @part = Part.new
    @makes = Make.all
    @models = Model.all
    @years = Year.all
  end

  def create
    @part = Part.new(part_params)
    if @part.save
      redirect_to @part
    else
      render :new
    end
  end

  def edit
    @part = Part.find(params[:id])
  end

  def update
    @part = Part.find(params[:id])
    if @part.update(part_params)
      redirect_to @part
    else
      render :edit
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy
    redirect_to parts_path
  end

  def import
    uploaded_file = params[:file] # Assuming you have a file input in your form
    file_path = uploaded_file.path

    ImportPartsJob.perform_now(file_path) # Use perform_now instead of perform_later

    flash[:notice] = "Import started successfully."
    redirect_to parts_path
  rescue => e
    flash[:alert] = "Import failed: #{e.message}"
    redirect_to parts_path
  end

  def export
    file_path = Rails.root.join('tmp', 'parts_export.csv').to_s # Convert to string
    ExportPartsJob.perform_later(file_path)

    flash[:notice] = "Export started. The file will be available for download shortly."
    redirect_to parts_path
  end

  def download_export
    file_path = Rails.root.join('tmp', 'parts_export.csv')

    if File.exist?(file_path)
      send_file file_path, type: 'text/csv', filename: 'parts_export.csv'
    else
      flash[:alert] = "Export file not found."
      redirect_to parts_path
    end
  end

  private

  def part_params
    params.require(:part).permit(
      :item_part_number,
      :part_number,
      :name,
      :description,
      :package_level_gtin,
      :height,
      :width,
      :length,
      :shipping_height,
      :shipping_width,
      :shipping_length,
      :weight,
      :price,
      :attribute_name,
      :product_attribute,
      :model_id,
      :year_id,
      :make_id,
      images: []
    )
  end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_part_list.html.erb
<div id="part-list" class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Part Name </th>
        <th>Item Part Number</th>
        <th>Part Number</th>
        <th>Description</th>
        <th>Package Level GTIN</th>
        <th>Height</th>
        <th>Width</th>
        <th>Length</th>
        <th>Shipping Height</th>
        <th>Shipping Width</th>
        <th>Shipping Length</th>
        <th>Weight</th>
        <th>Attribute Name</th>
        <th>Price</th>
        <th>Product Attribute</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @parts.each do |part| %>
        <tr>
          <td><h3><%= part.name %></h3></td>
          <td><%= part.item_part_number %></td>
          <td><%= part.part_number %></td>
          <td><%= part.description %></td>
          <td><%= part.package_level_gtin %></td>
          <td><%= part.height %></td>
          <td><%= part.width %></td>
          <td><%= part.length %></td>
          <td><%= part.shipping_height %></td>
          <td><%= part.shipping_width %></td>
          <td><%= part.shipping_length %></td>
          <td><%= part.weight %></td>
          <td><%= part.attribute_name %></td>
          <td><%= number_to_currency(part.price) %></td>
          <td><%= part.product_attribute %></td>
          <td>
            <%= link_to 'Show', part, class: 'btn btn-info btn-sm' %>
            <%= link_to 'Edit', edit_part_path(part), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/parts/add_to_cart.js.erb
$('#cart-count').text('<%= session[:cart].count %>');
$('#success-message').html('<div class="alert alert-success">Part added to cart successfully!</div>').show().delay(3000).fadeOut();

app/views/parts/add_to_cart_js.js.erb
$('#cart-count').text('<%= session[:cart].count %>');
$('#success-message').html('<div class="alert alert-success">Part added to cart successfully!</div>').show().delay(3000).fadeOut();

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= form_with(model: @part, local: true) do |form| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% @part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_part_number %>
    <%= form.text_field :item_part_number %>
  </div>

  <div class="field">
    <%= form.label :part_number %>
    <%= form.text_field :part_number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :package_level_gtin %>
    <%= form.text_field :package_level_gtin %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.text_field :width %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %>
  </div>

  <div class="field">
    <%= form.label :shipping_height %>
    <%= form.text_field :shipping_height %>
  </div>

  <div class="field">
    <%= form.label :shipping_width %>
    <%= form.text_field :shipping_width %>
  </div>

  <div class="field">
    <%= form.label :shipping_length %>
    <%= form.text_field :shipping_length %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :attribute_name %>
    <%= form.text_area :attribute_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :product_attribute %>
    <%= form.text_area :product_attribute %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<!-- app/views/parts/index.html.erb -->
<h1 class="mb-4">Parts List</h1>

<div class="mb-3">
  <input type="text" id="search" class="form-control" placeholder="Search parts...">
</div>

<div class="mb-3">
  <h5>Make</h5>
  <%= select_tag "q[model_make_id_eq]", options_from_collection_for_select(Make.all, :id, :name, { include_blank: true }), class: 'form-control' %>
</div>

<div class="mb-3">
  <h5>Model</h5>
  <%= select_tag "q[model_id_eq]", options_from_collection_for_select(Model.all, :id, :name, { include_blank: true }), class: 'form-control' %>
</div>

<div class="mb-3">
  <h5>Year</h5>
  <%= select_tag "q[year_id_eq]", options_from_collection_for_select(Year.all, :id, :year, { include_blank: true }), class: 'form-control' %>
</div>

<div class="mb-3">
  <h5>Price Range</h5>
  <select id="filter-price" class="form-control">
    <option value="">Select Price Range</option>
    <option value="0-100">0 - 100</option>
    <option value="101-200">101 - 200</option>
    <option value="201-300">201 - 300</option>
    <option value="301-400">301 - 400</option>
    <option value="401-500">401 - 500</option>
  </select>
</div>

<div class="mb-3">
  <%= form_with url: import_parts_path, local: true, method: :post, html: { multipart: true } do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Import Parts', class: 'btn btn-primary' %>
  <% end %>
</div>

<div class="mb-3">
  <%= link_to 'Export Parts', export_parts_path, class: 'btn btn-success' %>
  <%= link_to 'Download Export', download_export_parts_path, class: 'btn btn-info' %>
</div>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<div id="part-list" class="table-responsive">
  <table class="table table-striped">
    <tbody>
      <%= render partial: 'parts/part_list', locals: { parts: @parts } %>
    </tbody>
  </table>
</div>

<div class="my-3">
  <%= link_to 'New Part', new_part_path, class: 'btn btn-success' %>
  <%= link_to 'Order List', orders_path, class: 'btn btn-secondary' %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const searchInput = document.getElementById('search');
    const priceFilter = document.getElementById('filter-price');
    const makeFilter = document.querySelector('select[name="q[model_make_id_eq]"]');
    const modelFilter = document.querySelector('select[name="q[model_id_eq]"]');
    const yearFilter = document.querySelector('select[name="q[year_id_eq]"]');

    const fetchParts = () => {
      const query = searchInput.value;
      const priceRange = priceFilter.value;
      const makeId = makeFilter.value;
      const modelId = modelFilter.value;
      const yearId = yearFilter.value;

      // Construct the query string
      let url = `/parts/search?q[item_part_number_or_part_number_or_name_or_description_cont]=${query}`;
      if (makeId) {
        url += `&q[model_make_id_eq]=${makeId}`;
      }
      if (modelId) {
        url += `&q[model_id_eq]=${modelId}`;
      }
      if (yearId) {
        url += `&q[year_id_eq]=${yearId}`;
      }
      if (priceRange) {
        const [minPrice, maxPrice] = priceRange.split('-');
        url += `&q[price_gteq]=${minPrice}&q[price_lteq]=${maxPrice}`;
      }

      fetch(url)
        .then(response => response.text())
        .then(html => {
          document.getElementById('part-list').innerHTML = html;
        });
    };

    searchInput.addEventListener('input', fetchParts);
    priceFilter.addEventListener('change', fetchParts);
    makeFilter.addEventListener('change', fetchParts);
    modelFilter.addEventListener('change', fetchParts);
    yearFilter.addEventListener('change', fetchParts);
  });
</script>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= form_with(model: @part, local: true) do |form| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% @part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_part_number %>
    <%= form.text_field :item_part_number %>
  </div>

  <div class="field">
    <%= form.label :part_number %>
    <%= form.text_field :part_number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :package_level_gtin %>
    <%= form.text_field :package_level_gtin %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.text_field :width %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length %>
  </div>

  <div class="field">
    <%= form.label :shipping_height %>
    <%= form.text_field :shipping_height %>
  </div>

  <div class="field">
    <%= form.label :shipping_width %>
    <%= form.text_field :shipping_width %>
  </div>

  <div class="field">
    <%= form.label :shipping_length %>
    <%= form.text_field :shipping_length %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :attribute_name %>
    <%= form.text_area :attribute_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :product_attribute %>
    <%= form.text_area :product_attribute %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :model_id, "Model" %>
    <%= form.collection_select :model_id, Model.all, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :year_id, "Year" %>
    <%= form.collection_select :year_id, Year.all, :id, :year, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :make_id, "Make" %>
    <%= form.collection_select :make_id, Make.all, :id, :name, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', parts_path %>